"""Editor-only interface for the compiled Pybricks _solver.mpy module.

The uploader supplies the real native module; this stub is never executed.
"""

def start(state: bytes | bytearray) -> bytearray: ...
def step(ctx: bytearray, count: int, target: int, depth: int) -> int: ...
def best(ctx: bytearray) -> bytes: ...
def stats(ctx: bytearray) -> tuple[int, int, int, int]: ...
